### ISSUE TITLE
some basic questions.

### ISSUE THREAD

**Issue by yw3l** [barrel-0314/daco#2]
Dear @barrel-0314 ,
I am sorry to bother you here, some questions in my mind. 

1. In 'main function' of the 'Iteration_norm.py' file, the program ran on one table ? 
2. How can I run Daco on other datasets ?
when I ran the code provided, the program give prompt, which is `['10151359_0_8168779773862259178',...]
10151359_0_8168779773862259178,
n 0
`
yours,sincerely.

**Comment by thethe-github** [comment]
Hello, I encountered the same problem and the result after running the code is the same as yours. I am very sorry to ask how you solved it?

**Comment by yw3l** [comment]
Hello, I didn't solve it, I gave up.
